float32 min_circle_dist         # 10 - 200
uint32  min_radius              # 10 - 200
uint32  max_radius              # 100 - 600
uint16  filter_h_min            # 0 - 359
uint16  filter_h_max
uint16  filter_s_min            # 0 - 255
uint16  filter_s_max
uint16  filter_v_min            # 0 - 255
uint16  filter_v_max
uint16  filter2_h_min            # 0 - 359
uint16  filter2_h_max
uint16  filter2_s_min            # 0 - 255
uint16  filter2_s_max
uint16  filter2_v_min            # 0 - 255
uint16  filter2_v_max